# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  # config.vm.network :hostonly, "192.168.33.10"

  # Assign this VM to a bridged network, allowing you to connect directly to a
  # network using the host's network device. This makes the VM appear as another
  # physical device on your network.
  # config.vm.network :bridged

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.forward_port 80, 8080

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding 
  # some recipes and/or roles.
  #
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../cookbooks"
    chef.roles_path = "../roles"

    chef.add_role "vagrant" # You need to add this role with the default Vagrant
                            # basebox since Vagrant installs Ruby in its own way
                            # that is different from a clean Ubuntu install.
    chef.add_role "rails"
  
    # You may also specify custom JSON attributes:
    chef.json = { 
      "authorization" => {
        "sudo" => {
          "include_sudoers_d" => true,
          "users" => ["vagrant"],
          "passwordless" => true
        }
      },
      "active_applications" => {
        "apphakker" => {
          "domain_names" => ["localhost"],
          "packages" => ["libpq-dev", "nodejs"]
        }
      },
      "ssh_deploy_keys" => [
        "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzhkBf6REh0MTLJko7y8mxmqF+9Cn1CIUblYas+hOgawwwzUAG4zbikKEZrNd+79oyh1qBNZcwMljN0EKHwKgwGpEhxg7EGpRLtqD8ePGl5dOql1hIjP9Q+gw+eBjbpM1uBeWE5QaV0DEMQCVAOEn2Tr18mqNY/MGY9hSFUARGrXcBHERsbCNmEpnopUBpQO9OcgJDcMuO6kPWvCM5QfcU+88aaZq4ECOvw6NZKVP5Ovv+wNTP6SFAcCf0SZEU0ossCBtoI8V5lh+DK9ivxmvRHXbxZBYMY34HSqYZSrw60qzBBu4+Zi71Hq2N0/GwTLRcayxseWjLstnc6Gs7DahpQ== michiel@Michiel-Sikkess-MacBook-Pro.local"
      ],
    }
  end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision :chef_client do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # IF you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
