maintainer       "Alexander Zaytsev"
maintainer_email "alexander@say26.com"
license          "Apache 2.0"
description      "Installs/Configures backup gem"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
depends "sudo", "> 1.2.0"
depends "database"
depends "nginx"
depends "bluepill"